# Generated by Django 6.0.3 on 2026-04-13 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('app_token_prefix', models.CharField(db_index=True, max_length=24)),
                ('app_token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('inbound_email_alias', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='app_icons/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='app_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuietPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('period_type', models.CharField(choices=[('ONCE', 'One-time'), ('RECURRING', 'Recurring')], default='ONCE', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_days', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiet_periods', to='applications.application')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
