# Generated by Django 6.0.3 on 2026-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
