# Generated by Django 6.0.3 on 2026-06-17 22:59

import applications.url_safety
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_inbound_email_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, validators=[applications.url_safety.validate_webhook_url]),
        ),
    ]
