# Generated by Django 6.0.6 on 2026-07-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='enrolment_code',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='enrolment_code_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
