# Generated by Django 6.0.6 on 2026-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_send_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='legacy_send_last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
