# Generated by Django 6.0.3 on 2026-06-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceapplicationlink',
            name='unlink_source',
            field=models.CharField(blank=True, choices=[('device_button', 'Device button'), ('inbox', 'Inbox per-app unlink'), ('takeover', 'Push-token takeover by another user')], max_length=20),
        ),
        migrations.AddField(
            model_name='deviceapplicationlink',
            name='unlinked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
