# Generated by Django 6.0.6 on 2026-07-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_deviceapplicationlink_unlink_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceapplicationlink',
            name='unlink_source',
            field=models.CharField(blank=True, choices=[('device_button', 'Device button'), ('inbox', 'Inbox per-app unlink'), ('takeover', 'Push-token takeover by another user'), ('owner_eviction', 'Evicted by the application owner')], max_length=20),
        ),
    ]
