# Generated by Django 6.0.6 on 2026-07-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('FR', 'French'), ('NL', 'Dutch'), ('EN', 'English'), ('IT', 'Italian'), ('ES', 'Spanish')], default='FR', max_length=2),
        ),
    ]
