# Generated by Django 6.0.3 on 2026-06-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_webhook_url'),
        ('devices', '0002_device_user'),
        ('notifications', '0002_notificationtemplate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_d8d933_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['application', 'status'], name='notificatio_applica_ce7d40_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_e5e8a7_idx'),
        ),
    ]
