# Generated by Django 6.0.3 on 2026-06-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notificatio_status_d8d933_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
