# Generated by Django 6.0.3 on 2026-06-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationdelivery_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
